### ISSUE TITLE
how to deal with other imgs?

### ISSUE THREAD

**Issue by DayDayUpUpUp666** [thwjoy/densecrf_ho#1]
Dear author,
     How to test other images? And does it need to be loaded unary file everytime?

**Comment by thwjoy** [comment]
Sorry for the late reply!

So in order to test new images, you need to provide the colour image and an associated unary file - which is essentially an array of class scores per pixel. We didn't generate the unaries ourselves for this, as we used the existing ones supplied here http://graphics.stanford.edu/projects/densecrf/unary. If you want to generate your own unaries, more information can be found here http://graphics.stanford.edu/projects/densecrf/unary.

Hope this helps!
